### PR TITLE
Fix Button Visibility Issue on Bug Bounties Page

### PR DESCRIPTION
**Pull request by mAHA6-STAR**
## Summary
This pull request addresses an issue where the "MORE INFO" button on the Bug Bounties page was not visible by default and only appeared on hover. The button is now visible at all times and changes color when hovered over.

## Changes Made
- Updated the HTML structure for the "MORE INFO" button.
- Added inline styles to ensure the button is always visible.
- Applied hover state styles for better user experience.

## Testing
- Verified that the button is visible by default.
- Confirmed that the button changes color on hover.

## Screenshots

Screenshot 2024-07-08 at 1 28 41 PM

### CODE REVIEW

**Review by DonnieBLT — APPROVED** [review]
Thank you!

**Review by DonnieBLT — APPROVED** [review]

**Comment by MAHALAKSHMImahalakshmi** [comment]
HI sir,
Sorry for the late reply sir, actually trying to run in a local machine to
pass the test case then i get access to merge it.
But I am facing an issue from installing a local set that current python
3.11.5 does not support poetry shell where it can be accessed through
3.11.2. I deleted lattes version and tried to reinstall the old version but
not getting verification of 3.11.2.I also looked at a video for setting up
but did get a solution to solve it .Can you please guide me sir for the
issue.
Thank you sir for your encouragement and support.

regards Mahalakshmi

**Comment by MAHALAKSHMImahalakshmi** [comment]
Hi,

I am currently encountering an issue while trying to run a local setup to pass test cases before merging a pull request. My Poetry-managed project requires Python 3.11.2. However, my current setup has Python 3.11.5, which does not support the Poetry shell for this project.

I attempted to uninstall Python 3.11.5 and reinstall Python 3.11.2, but I faced issues verifying the installation of Python 3.11.2. I also referred to several setup guides and videos but could not find a solution to resolve this issue.

Steps Taken:

Uninstalled Python 3.11.5.
Attempted to install Python 3.11.2.
Faced verification issues with Python 3.11.2 installation.
Request:

Could you please provide guidance on correctly setting up Python 3.11.2 for my project to ensure compatibility with Poetry shell? Any detailed steps or troubleshooting tips would be greatly appreciated.

Thank you for your support and encouragement.

Best regards,
Mahalakshmi R

**Review by DonnieBLT — CHANGES_REQUESTED** [review]
please format with pre-commit

**Pull request closed without merging**
